language: go

go:
  - 1.x

os:
  - linux

env:
  global:
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"
    
go_import_path: github.com/Oppodelldog/docker-dns

services:
  - docker

script:
  - docker pull golang:1.14.4
  - go run test/main.go