version: '3.0'
services:

  dns-lookup:
    command: go run dnslookup/main.go
    image: golang:1.11.0
    volumes:
    - ./:/go/src/github.com/Oppodelldog/docker-dns
    working_dir: /go/src/github.com/Oppodelldog/docker-dns
    dns:
    - 172.16.0.3
    networks:
      - app_net

  pong:
    command: go run pong/main.go
    image: golang:1.11.0
    volumes:
    - ./:/go/src/github.com/Oppodelldog/docker-dns
    working_dir: /go/src/github.com/Oppodelldog/docker-dns
    networks:
      - app_net

  dumb-dns:
    command: go run cmd/main.go
    image: golang:1.11.0
    volumes:
    - ./:/go/src/github.com/Oppodelldog/docker-dns
    - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/Oppodelldog/docker-dns/dnsserver
    networks:
      app_net:
        ipv4_address:  172.16.0.3


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24